//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedHouseManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargeTable
    {
        public int ChargeID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<int> HouseID { get; set; }
        public Nullable<bool> IsPaying { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> ProductID { get; set; }
    }
}
