//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedHouseManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsBought
    {
        public int ProductID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<float> Price { get; set; }
        public string Description { get; set; }
        public string ProductGroup { get; set; }
        public Nullable<int> UserPaidFull { get; set; }
        public Nullable<int> HouseID { get; set; }
        public string Name { get; set; }
    }
}
