//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedHouseManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SHMSUserDataConnectionString : DbContext
    {
        public SHMSUserDataConnectionString()
            : base("name=SHMSUserDataConnectionString")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<spGetAllHouseMates_Result> spGetAllHouseMates(Nullable<int> houseID)
        {
            var houseIDParameter = houseID.HasValue ?
                new ObjectParameter("HouseID", houseID) :
                new ObjectParameter("HouseID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetAllHouseMates_Result>("spGetAllHouseMates", houseIDParameter);
        }
    
        public virtual ObjectResult<string> spGetHashedPassword(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spGetHashedPassword", emailParameter);
        }
    }
}
